services:
  postgres:
    image: postgres:17.6
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: always

  app:
    container_name: nodup
    build:
      target: production
      args:
        DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      - postgres
